apiVersion: v1
kind: Secret
metadata:
  name: penny-wise-secret
type: Opaque
data: 
  MONGODB_URL: bW9uZ29kYWI6amVsbGFwYXZhbi9iZXBvc2l0aXZlQHBhbmt0aW5naG9sZGVyQG11bmdvL3Bhbmt0aW5nZG9hYm9vcm4vP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  SECRET_KEY: bXlzZWNyZXRrZXk=
